package GUI.Consulta;
import Fuente.CLS_Universidad;
import Fuente.CNA_Jugador;
import Fuente.CND_Año;
import Fuente.CND_Equipo;
import Fuente.CNS_Categoria;
import Fuente.CNS_Universidad;
import javax.swing.JFrame;

public class Consultar extends javax.swing.JFrame {

    /**
     * Creates new form Consultar
     */
    
    private CND_Año aux = new CND_Año (); 
    
    public Consultar(CND_Año aux) {
        
        initComponents();
        this.aux=aux;
        
    }
     public void cerrarTabs(){
        
        if(Consulta.getTabCount()>1){
            int aux=Consulta.getTabCount();
            for(int i=1; i<aux;i++){
                Consulta.removeTabAt(1);
            }  
        }
    }

    private Consultar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Consulta = new javax.swing.JTabbedPane();
        Año = new javax.swing.JPanel();
        jugBuscado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        verUniversidades = new javax.swing.JButton();
        display = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultar Información");

        jugBuscado.setToolTipText("escriba el nombre del jugador ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("Nombre del jugador");

        Buscar.setText("Buscar Jugador");
        Buscar.setToolTipText("busca el jugador en el torneo");
        Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarMouseClicked(evt);
            }
        });

        verUniversidades.setText("Ver Universidades");
        verUniversidades.setToolTipText("muestra las universidades inscritas");
        verUniversidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verUniversidadesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AñoLayout = new javax.swing.GroupLayout(Año);
        Año.setLayout(AñoLayout);
        AñoLayout.setHorizontalGroup(
            AñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AñoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verUniversidades)
                    .addGroup(AñoLayout.createSequentialGroup()
                        .addComponent(jugBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Buscar))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(172, Short.MAX_VALUE))
            .addComponent(display)
        );
        AñoLayout.setVerticalGroup(
            AñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AñoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verUniversidades)
                .addGap(18, 18, 18)
                .addGroup(AñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Consulta.addTab("Año", Año);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Consulta)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Consulta)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verUniversidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verUniversidadesMouseClicked
        // TODO add your handling code here:
            abrirTabUniversidades(aux);
    }//GEN-LAST:event_verUniversidadesMouseClicked

    private void BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarMouseClicked
        // TODO add your handling code here:
        CNS_Universidad uniAux = aux.getUniversidades().getCabeza();
        CNS_Categoria catAux = uniAux.getCategorias().getCabeza();
        CND_Equipo equipAux = catAux.getEquipos().getCabeza();
        CNA_Jugador jugAux1; //= equipAux.getAtletas().getRaiz();
        
        while(aux != null)
        {
            while(uniAux != null)
            {
                while(catAux != null)
                {
                    while(equipAux != null)
                    {
                        jugAux1 = equipAux.getAtletas().buscar(equipAux.getAtletas().getRaiz(), jugBuscado.getText());
                        if(jugAux1.getNombre().equalsIgnoreCase(jugBuscado.getText()))
                        {
                            System.out.println("ENCONTRADO!");
                            CNA_Jugador jugAux2=jugAux1;
                            InfoJug VentanaJugador = new InfoJug(jugAux2);
                            VentanaJugador.setVisible(true);
                            VentanaJugador.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                            //break;
                        } 
                        equipAux = equipAux.getProx();
                    }
                    catAux = catAux.getProx();
                }
                uniAux = uniAux.getProx();
            }
            aux = aux.getProx();
        }
        jugBuscado.setText("");
    }//GEN-LAST:event_BuscarMouseClicked
public void abrirTabUniversidades (CND_Año nodoAño){

           
            String NombreAño = Integer.toString(nodoAño.getAño());
            cerrarTabs();
            Consulta.addTab("Año "+NombreAño, new TabUniversidades(nodoAño.getUniversidades()));
            this.pack();
            Consulta.setSelectedIndex(1);
        
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Año;
    private javax.swing.JButton Buscar;
    private javax.swing.JTabbedPane Consulta;
    private javax.swing.JTextField display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jugBuscado;
    private javax.swing.JButton verUniversidades;
    // End of variables declaration//GEN-END:variables
}
