/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Consulta;
import Fuente.CNS_Categoria;
import Fuente.CLS_Categoria;
import javax.swing.JTabbedPane;

/**
 *
 * @author Jose Luis
 */
public class TabCategorias extends javax.swing.JPanel {

    /**
     * Creates new form TabCategorias
     */
    
     private CLS_Categoria listaCategoria;
     
    public TabCategorias(CLS_Categoria listaCat) {
        initComponents();
        listaCategoria= listaCat;
        llenarListategoriasBox ();
    }
    
    public void llenarListategoriasBox (){
    //listaUniversidades.addItem(""); // Combo Box
    CNS_Categoria NodoAux;
    NodoAux = listaCategoria.getCabeza();
        while(NodoAux!=null){
        listaCategoriasBox.addItem(NodoAux.getNumCat());
        NodoAux=NodoAux.getProx();
        }
    }
    
        public void cerrarTabs(){
        JTabbedPane padre=(JTabbedPane)this.getParent();
         if(padre!=null){
            if(((JTabbedPane)this.getParent()).getTabCount()>2){
                int aux=((JTabbedPane)this.getParent()).getTabCount();
                    for(int i=2; i<aux;i++){
                    ((JTabbedPane)this.getParent()).removeTabAt(3);
                    }  
                }  
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Categoria = new javax.swing.JPanel();
        listaCategoriasBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        verEquipo = new javax.swing.JButton();
        eliminarCat = new javax.swing.JButton();
        display = new javax.swing.JTextField();

        jLabel2.setText("Seleccione la Categoria");

        verEquipo.setText("Ver Equipos");
        verEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verEquipoMouseClicked(evt);
            }
        });

        eliminarCat.setText("Eliminar Categoria");
        eliminarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CategoriaLayout = new javax.swing.GroupLayout(Categoria);
        Categoria.setLayout(CategoriaLayout);
        CategoriaLayout.setHorizontalGroup(
            CategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CategoriaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(CategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(listaCategoriasBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eliminarCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        CategoriaLayout.setVerticalGroup(
            CategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoriaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(CategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CategoriaLayout.createSequentialGroup()
                        .addComponent(listaCategoriasBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(CategoriaLayout.createSequentialGroup()
                        .addComponent(verEquipo)
                        .addGap(14, 14, 14)
                        .addComponent(eliminarCat)))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(display)
            .addComponent(Categoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void verEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verEquipoMouseClicked
        // TODO add your handling code here:
        int numCat = Integer.parseInt(listaCategoriasBox.getSelectedItem().toString());
        CNS_Categoria auxCat = listaCategoria.buscar(numCat);
        abrirEquipos (auxCat);
    }//GEN-LAST:event_verEquipoMouseClicked

    private void eliminarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCatActionPerformed
        // TODO add your handling code here:
         int num = Integer.parseInt(listaCategoriasBox.getSelectedItem().toString());
          if(listaCategoria.buscar(num) != null)
          {
              listaCategoria.eliminarPosicion(listaCategoria.buscarParaEliminar(num));
              listaCategoriasBox.removeAllItems();
              llenarListategoriasBox ();
              display.setText("Catgoria eliminada satisfactoriamente");
          }
          else
          {
              display.setText("Error! No has seleccionado ninguna categoria");
          }
    }//GEN-LAST:event_eliminarCatActionPerformed

private void abrirEquipos (CNS_Categoria nodoCat)
{
            //cerrarTabs();
            String numeroCat = Integer.toString((nodoCat.getNumCat()));
            ((JTabbedPane)this.getParent()).addTab("Categoria "+numeroCat, new TabEquipos(nodoCat.getEquipos()));
            ((JTabbedPane)this.getParent()).setSelectedIndex(3);
            display.setText("");
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Categoria;
    private javax.swing.JTextField display;
    private javax.swing.JButton eliminarCat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox listaCategoriasBox;
    private javax.swing.JButton verEquipo;
    // End of variables declaration//GEN-END:variables
}
